import type { Metadata } from "next";
import "./globals.css";
import { SupportChat } from "@/widgets/support-chat";

export const metadata: Metadata = {
  title: "INTERLINK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`} suppressHydrationWarning>
        {children}
        <SupportChat />
      </body>
    </html>
  );
}
